nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.2.0.cjs

npmScopes:
  difuks:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: ${PERSONAL_NPM_TOKEN}

packageExtensions:
  react-cosmos-plugin@*:
    dependencies:
      glob: "*"
      resolve-from: "*"
  webpack-dev-middleware@*:
    dependencies:
      webpack: "*"
