name: 'Publish npm package'
description: 'Publish npm package'
inputs:
  package-name:
    description: 'Name of package'
    required: true
  package-dir:
    description: 'Directory of package'
    required: true

runs:
  using: composite
  steps:
    - name: Set path filter
      uses: dorny/paths-filter@v2
      id: path-filter
      with:
        filters: |
          ${{ inputs.package-name }}:
            - '${{inputs.package-dir}}/**'

    - name: Commit message check
      id: check-strategy
      if: steps.path-filter.outputs[inputs.package-name] == 'true'
      shell: bash
      run: |
        isMinor=${{ contains(github.event.head_commit.message, 'feat(${{ inputs.package-name }})') }}
        isPatch=${{ contains(github.event.head_commit.message, 'fix(${{ inputs.package-name }})') }}
        
        if [$isMinor == 'true']
        then
          echo "::set-output name=strategy::minor"
        elif [$isPatch == 'true']
          echo "::set-output name=strategy::patch"
        else
          echo "::set-output name=strategy::patch"

    - name: Publish
      if: steps.path-filter.outputs[inputs.package-name] == 'true'
      shell: bash
      run: yarn workspace @difuks/${{ inputs.package-name }} version ${{ steps.check-strategy.outputs.strategy }}
