name: 'Run ssh script'
description: 'Run ssh script'
inputs:
  script:
    description: 'Script for run'
    required: true
  secret-context:
    description: 'Secret params'
    required: true

runs:
  using: composite
  steps:
    - name: Run node script
      uses: appleboy/ssh-action@master
      env:
        FUKS_BLOG_AUTH_POSTGRES_PASSWORD: ${{ inputs.secret-context.FUKS_BLOG_AUTH_POSTGRES_PASSWORD }}
        FUKS_BLOG_AUTH_POSTGRES_USER: ${{ inputs.secret-context.FUKS_BLOG_AUTH_POSTGRES_USER }}
        FUKS_BLOG_AUTH_POSTGRES_HOST: fuks-blog-auth-postgres

        FUKS_BLOG_BACKEND_POSTGRES_PASSWORD: ${{ inputs.secret-context.FUKS_BLOG_BACKEND_POSTGRES_PASSWORD }}
        FUKS_BLOG_BACKEND_POSTGRES_USER: ${{ inputs.secret-context.FUKS_BLOG_BACKEND_POSTGRES_USER }}
        FUKS_BLOG_BACKEND_POSTGRES_HOST: ${{ inputs.secret-context.FUKS_BLOG_BACKEND_POSTGRES_HOST }}

        PERSONAL_NPM_TOKEN: ${{ inputs.secret-context.PERSONAL_NPM_TOKEN }}
        FUKS_BLOG_AUTH_JWT_SECRET: ${{ inputs.secret-context.FUKS_BLOG_AUTH_JWT_SECRET }}
      with:
        host: ${{ inputs.secret-context.SSH_HOST }}
        username: ${{ inputs.secret-context.SSH_USERNAME }}
        key: ${{ inputs.secret-context.SSH_PRIVATE_KEY }}
        script_stop: true
        envs: >
          FUKS_BLOG_AUTH_POSTGRES_PASSWORD,
          FUKS_BLOG_AUTH_POSTGRES_USER,
          FUKS_BLOG_AUTH_POSTGRES_HOST,
          FUKS_BLOG_BACKEND_POSTGRES_USER,
          FUKS_BLOG_BACKEND_POSTGRES_PASSWORD,
          PERSONAL_NPM_TOKEN,
          FUKS_BLOG_AUTH_JWT_SECRET
        script: ${{inputs.script}}
