name: 'Run ssh script'
description: 'Run ssh script'
inputs:
  script:
    description: 'Script for run'
    required: true
  secret-context:
    description: 'Secret params'
    required: true

runs:
  using: composite
  steps:
    - name: Run node script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.secret-context.SSH_HOST }}
        username: ${{ inputs.secret-context.SSH_USERNAME }}
        key: ${{ inputs.secret-context.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          export FUKS_BLOG_AUTH_POSTGRES_PASSWORD="${{ inputs.secret-context.FUKS_BLOG_AUTH_POSTGRES_PASSWORD }}"
          export FUKS_BLOG_AUTH_POSTGRES_USER: "${{ inputs.secret-context.FUKS_BLOG_AUTH_POSTGRES_USER }}"
          export FUKS_BLOG_AUTH_POSTGRES_HOST: "fuks-blog-auth-postgres"
  
          export FUKS_BLOG_BACKEND_POSTGRES_PASSWORD: "${{ inputs.secret-context.FUKS_BLOG_BACKEND_POSTGRES_PASSWORD }}"
          export FUKS_BLOG_BACKEND_POSTGRES_USER: "${{ inputs.secret-context.FUKS_BLOG_BACKEND_POSTGRES_USER }}"
          export FUKS_BLOG_BACKEND_POSTGRES_HOST: "fuks-blog-backend-postgres"
  
          export PERSONAL_NPM_TOKEN: "${{ inputs.secret-context.PERSONAL_NPM_TOKEN }}"
          export FUKS_BLOG_AUTH_JWT_SECRET: "${{ inputs.secret-context.FUKS_BLOG_AUTH_JWT_SECRET }}"

          ${{inputs.script}}
