name: Build and deploy

on:
  push:
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Build libs
        run: yarn build:lib

      - name: Eslint
        run: yarn lint

      - name: Build packages
        run: yarn build
