name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_RECAPTCHA_CLIENT_KEY: ${{ secrets.GOOGLE_RECAPTCHA_CLIENT_KEY }}
      PERSONAL_NPM_TOKEN: ${{ secrets.PERSONAL_NPM_TOKEN }}
      FUKS_BLOG_AUTH_GOOGLE_CLIENT_ID: ${{ secrets.FUKS_BLOG_AUTH_GOOGLE_CLIENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install modules
        run: yarn install

      - name: Build libs
        run: yarn build:lib

      - name: Eslint
        run: yarn lint

      - name: E2E tests
        run: yarn e2e

      - name: Build entries
        run: yarn build

      - name: Build typedoc
        run: yarn typedoc

      - name: Check packages versions
        run: yarn version check
